export const mechaAssetBase = "/dashboard/assets/mecha";

const icon = (name: string, state: "default" | "hover" | "active" | "disabled" = "default", size: 16 | 20 | 24 | 32 = 20) =>
  `${mechaAssetBase}/icons/${name}/${state}-${size}.png`;

export const mechaAssets = {
  branding: {
    logo: `${mechaAssetBase}/branding/logo-primary.png`,
    icon: `${mechaAssetBase}/branding/logo-icon.png`,
    monochrome: `${mechaAssetBase}/branding/logo-monochrome.svg`,
    favicon16: `${mechaAssetBase}/branding/favicon-16.png`,
    favicon32: `${mechaAssetBase}/branding/favicon-32.png`,
    favicon64: `${mechaAssetBase}/branding/favicon-64.png`,
    appIcon512: `${mechaAssetBase}/branding/app-icon-512.png`,
  },
  backgrounds: {
    app: `${mechaAssetBase}/backgrounds/bg-app.webp`,
    appMobile: `${mechaAssetBase}/backgrounds/bg-app-mobile.webp`,
    sidebar: `${mechaAssetBase}/backgrounds/bg-sidebar.webp`,
    header: `${mechaAssetBase}/backgrounds/bg-header.webp`,
    controlRoom: `${mechaAssetBase}/backgrounds/bg-control-room.webp`,
    controlRoomMobile: `${mechaAssetBase}/backgrounds/bg-control-room-mobile.webp`,
    grid: `${mechaAssetBase}/backgrounds/bg-grid-texture.png`,
    stars: `${mechaAssetBase}/backgrounds/bg-stars-texture.png`,
    panelNoise: `${mechaAssetBase}/backgrounds/bg-panel-noise.png`,
    emptyState: `${mechaAssetBase}/backgrounds/bg-empty-state.webp`,
  },
  frames: {
    cardDefault: `${mechaAssetBase}/frames/frame-card-default.9.png`,
    cardActive: `${mechaAssetBase}/frames/frame-card-active.9.png`,
    cardDanger: `${mechaAssetBase}/frames/frame-card-danger.9.png`,
    modal: `${mechaAssetBase}/frames/frame-modal.9.png`,
    tooltip: `${mechaAssetBase}/frames/frame-tooltip.9.png`,
    sidebarActive: `${mechaAssetBase}/frames/frame-sidebar-active.9.png`,
    dividerHorizontal: `${mechaAssetBase}/frames/divider-horizontal.png`,
    dividerVertical: `${mechaAssetBase}/frames/divider-vertical.png`,
    corners: {
      topLeft: `${mechaAssetBase}/frames/corner-decoration-tl.png`,
      topRight: `${mechaAssetBase}/frames/corner-decoration-tr.png`,
      bottomLeft: `${mechaAssetBase}/frames/corner-decoration-bl.png`,
      bottomRight: `${mechaAssetBase}/frames/corner-decoration-br.png`,
    },
  },
  icons: {
    get: icon,
    dashboard: icon("dashboard"),
    apiKeys: icon("api-keys"),
    models: icon("models"),
    history: icon("history"),
    system: icon("system"),
    refresh: icon("refresh"),
    search: icon("search"),
    filter: icon("filter"),
    settings: icon("settings"),
    add: icon("add"),
    edit: icon("edit"),
    delete: icon("delete"),
    copy: icon("copy"),
    download: icon("download"),
    upload: icon("upload"),
    logout: icon("logout"),
    more: icon("more"),
    play: icon("play"),
    restart: icon("restart"),
    stop: icon("stop"),
  },
  status: {
    online: `${mechaAssetBase}/status/online.png`,
    offline: `${mechaAssetBase}/status/offline.png`,
    connecting: `${mechaAssetBase}/status/connecting.png`,
    healthy: `${mechaAssetBase}/status/healthy.png`,
    degraded: `${mechaAssetBase}/status/degraded.png`,
    warning: `${mechaAssetBase}/status/warning.png`,
    error: `${mechaAssetBase}/status/error.png`,
    success: `${mechaAssetBase}/status/success.png`,
    processing: `${mechaAssetBase}/status/processing.png`,
    locked: `${mechaAssetBase}/status/locked.png`,
    unlocked: `${mechaAssetBase}/status/unlocked.png`,
  },
  metrics: {
    service: `${mechaAssetBase}/metrics/service.png`,
    modelCore: `${mechaAssetBase}/metrics/model-core.png`,
    requests: `${mechaAssetBase}/metrics/requests.png`,
    uptime: `${mechaAssetBase}/metrics/uptime.png`,
    successRate: `${mechaAssetBase}/metrics/success-rate.png`,
    latency: `${mechaAssetBase}/metrics/latency.png`,
    memory: `${mechaAssetBase}/metrics/memory.png`,
    proxy: `${mechaAssetBase}/metrics/proxy.png`,
    worker: `${mechaAssetBase}/metrics/worker.png`,
    circuitBreaker: `${mechaAssetBase}/metrics/circuit-breaker.png`,
  },
  mascot: {
    avatar64: `${mechaAssetBase}/mascot/aria-avatar-64.png`,
    avatar128: `${mechaAssetBase}/mascot/aria-avatar-128.png`,
    idle: `${mechaAssetBase}/mascot/aria-idle.png`,
    success: `${mechaAssetBase}/mascot/aria-success.png`,
    warning: `${mechaAssetBase}/mascot/aria-warning.png`,
    error: `${mechaAssetBase}/mascot/aria-error.png`,
    loading1: `${mechaAssetBase}/mascot/aria-loading-01.png`,
    loading2: `${mechaAssetBase}/mascot/aria-loading-02.png`,
    emptyApiKey: `${mechaAssetBase}/mascot/aria-empty-api-key.png`,
    emptyHistory: `${mechaAssetBase}/mascot/aria-empty-history.png`,
    testModel: `${mechaAssetBase}/mascot/aria-test-model.png`,
    systemHealth: `${mechaAssetBase}/mascot/aria-system-health.png`,
    mechaSilhouette: `${mechaAssetBase}/mascot/mecha-silhouette.webp`,
    controlRoom: `${mechaAssetBase}/mascot/mecha-control-room.webp`,
    drone: `${mechaAssetBase}/mascot/drone-mascot.png`,
    droneConnected: `${mechaAssetBase}/mascot/drone-connected.png`,
    droneError: `${mechaAssetBase}/mascot/drone-error.png`,
  },
  buttons: {
    primary: `${mechaAssetBase}/buttons/button-primary-bg.png`,
    primaryHover: `${mechaAssetBase}/buttons/button-primary-hover-bg.png`,
    secondary: `${mechaAssetBase}/buttons/button-secondary-bg.png`,
    secondaryHover: `${mechaAssetBase}/buttons/button-secondary-hover-bg.png`,
    danger: `${mechaAssetBase}/buttons/button-danger-bg.png`,
    dangerHover: `${mechaAssetBase}/buttons/button-danger-hover-bg.png`,
    iconFrame: `${mechaAssetBase}/buttons/button-icon-frame.png`,
    sparkle: `${mechaAssetBase}/buttons/button-corner-sparkle.png`,
  },
  states: {
    emptyApiKeys: `${mechaAssetBase}/states/empty-api-keys.webp`,
    emptyModels: `${mechaAssetBase}/states/empty-models.webp`,
    emptyHistory: `${mechaAssetBase}/states/empty-history.webp`,
    emptyProxy: `${mechaAssetBase}/states/empty-proxy.webp`,
    loadingCore: `${mechaAssetBase}/states/loading-core.webp`,
    disconnected: `${mechaAssetBase}/states/disconnected.webp`,
    serverError: `${mechaAssetBase}/states/server-error.webp`,
    accessDenied: `${mechaAssetBase}/states/access-denied.webp`,
    testSuccess: `${mechaAssetBase}/states/test-success.webp`,
    testFailed: `${mechaAssetBase}/states/test-failed.webp`,
  },
} as const;

export type MechaAssets = typeof mechaAssets;
